import { Category, MenuItem, Order } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Burgers", slug: "burgers", icon: "🍔", color: "#FF6B35" },
  { id: "2", name: "Pizza", slug: "pizza", icon: "🍕", color: "#E55520" },
  { id: "3", name: "Sushi", slug: "sushi", icon: "🍱", color: "#06D6A0" },
  { id: "4", name: "Pasta", slug: "pasta", icon: "🍝", color: "#FFD166" },
  { id: "5", name: "Salads", slug: "salads", icon: "🥗", color: "#4CAF50" },
  { id: "6", name: "Desserts", slug: "desserts", icon: "🍰", color: "#FF69B4" },
  { id: "7", name: "Drinks", slug: "drinks", icon: "🥤", color: "#2196F3" },
  { id: "8", name: "Chicken", slug: "chicken", icon: "🍗", color: "#FF9800" },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    id: "1",
    name: "Double Smash Burger",
    description: "Two juicy smash patties with cheddar, caramelized onions, pickles & special sauce on a brioche bun.",
    price: 14.99,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
    category_id: "1",
    rating: 4.8,
    review_count: 342,
    prep_time: 15,
    is_available: true,
    is_featured: true,
    tags: ["bestseller", "spicy"],
  },
  {
    id: "2",
    name: "Margherita Suprema",
    description: "San Marzano tomatoes, fresh mozzarella di bufala, basil leaves, extra virgin olive oil.",
    price: 18.50,
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80",
    category_id: "2",
    rating: 4.9,
    review_count: 521,
    prep_time: 20,
    is_available: true,
    is_featured: true,
    tags: ["vegetarian", "classic"],
  },
  {
    id: "3",
    name: "Dragon Roll",
    description: "Shrimp tempura inside, avocado on top, eel sauce & sesame seeds.",
    price: 22.00,
    image_url: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=500&q=80",
    category_id: "3",
    rating: 4.7,
    review_count: 189,
    prep_time: 25,
    is_available: true,
    is_featured: true,
    tags: ["seafood", "premium"],
  },
  {
    id: "4",
    name: "Truffle Carbonara",
    description: "Al dente spaghetti with guanciale, pecorino romano, eggs, black pepper & shaved truffle.",
    price: 21.00,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&q=80",
    category_id: "4",
    rating: 4.6,
    review_count: 267,
    prep_time: 18,
    is_available: true,
    is_featured: false,
    tags: ["premium", "italian"],
  },
  {
    id: "5",
    name: "Crispy Chicken Sandwich",
    description: "Buttermilk-fried chicken breast, spicy mayo, coleslaw & pickles on a toasted potato bun.",
    price: 13.50,
    image_url: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=500&q=80",
    category_id: "8",
    rating: 4.7,
    review_count: 412,
    prep_time: 15,
    is_available: true,
    is_featured: true,
    tags: ["bestseller", "crispy"],
  },
  {
    id: "6",
    name: "Greek Goddess Salad",
    description: "Romaine, kalamata olives, cherry tomatoes, cucumber, feta, pepperoncini & lemon herb dressing.",
    price: 12.00,
    image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&q=80",
    category_id: "5",
    rating: 4.4,
    review_count: 156,
    prep_time: 10,
    is_available: true,
    is_featured: false,
    tags: ["healthy", "vegetarian"],
  },
  {
    id: "7",
    name: "Chocolate Lava Cake",
    description: "Warm dark chocolate fondant with vanilla bean ice cream & raspberry coulis.",
    price: 9.50,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&q=80",
    category_id: "6",
    rating: 4.9,
    review_count: 298,
    prep_time: 12,
    is_available: true,
    is_featured: true,
    tags: ["dessert", "indulgent"],
  },
  {
    id: "8",
    name: "Spicy BBQ Chicken Pizza",
    description: "Smoky BBQ sauce, grilled chicken, red onions, jalapeños, mozzarella & cilantro.",
    price: 20.00,
    image_url: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&q=80",
    category_id: "2",
    rating: 4.5,
    review_count: 334,
    prep_time: 22,
    is_available: true,
    is_featured: false,
    tags: ["spicy", "bbq"],
  },
  {
    id: "9",
    name: "Wagyu Beef Burger",
    description: "A5 Wagyu patty, aged cheddar, truffle aioli, arugula & heirloom tomato.",
    price: 34.99,
    image_url: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=500&q=80",
    category_id: "1",
    rating: 4.9,
    review_count: 97,
    prep_time: 20,
    is_available: true,
    is_featured: true,
    tags: ["premium", "wagyu"],
  },
  {
    id: "10",
    name: "Mango Lassi",
    description: "Chilled blend of Alphonso mango, yogurt, cardamom & a hint of rose water.",
    price: 6.50,
    image_url: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=500&q=80",
    category_id: "7",
    rating: 4.6,
    review_count: 201,
    prep_time: 5,
    is_available: true,
    is_featured: false,
    tags: ["drink", "refreshing"],
  },
  {
    id: "11",
    name: "Salmon Sashimi Set",
    description: "9 pieces of premium Atlantic salmon sashimi with pickled ginger & wasabi.",
    price: 28.00,
    image_url: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=500&q=80",
    category_id: "3",
    rating: 4.8,
    review_count: 143,
    prep_time: 15,
    is_available: true,
    is_featured: false,
    tags: ["seafood", "premium", "raw"],
  },
  {
    id: "12",
    name: "Buffalo Wings (12pc)",
    description: "Crispy chicken wings tossed in fiery buffalo sauce, served with blue cheese dip & celery.",
    price: 16.99,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=500&q=80",
    category_id: "8",
    rating: 4.7,
    review_count: 389,
    prep_time: 20,
    is_available: true,
    is_featured: true,
    tags: ["spicy", "sharing", "bestseller"],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_abc123001",
    user_id: "user_1",
    status: "preparing",
    total_price: 52.48,
    delivery_fee: 5.00,
    discount: 0.50,
    delivery_address: "123 Main St, Dhaka 1200",
    payment_method: "card",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    estimated_delivery: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
    items: [
      {
        id: "oi_001",
        menu_item_id: "1",
        menu_item_name: "Double Smash Burger",
        menu_item_image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&q=80",
        quantity: 2,
        price: 14.99,
      },
      {
        id: "oi_002",
        menu_item_id: "10",
        menu_item_name: "Mango Lassi",
        menu_item_image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=500&q=80",
        quantity: 2,
        price: 6.50,
      },
    ],
    rider: { name: "Rahim Uddin", phone: "+880 1700 000123", rating: 4.9 },
  },
  {
    id: "ord_abc123002",
    user_id: "user_1",
    status: "delivered",
    total_price: 44.49,
    delivery_fee: 5.00,
    discount: 0.50,
    delivery_address: "123 Main St, Dhaka 1200",
    payment_method: "card",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
    items: [
      {
        id: "oi_003",
        menu_item_id: "2",
        menu_item_name: "Margherita Suprema",
        menu_item_image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80",
        quantity: 2,
        price: 18.50,
      },
    ],
    rider: { name: "Karim Hossain", phone: "+880 1800 000456", rating: 4.8 },
  },
  {
    id: "ord_abc123003",
    user_id: "user_1",
    status: "delivered",
    total_price: 67.97,
    delivery_fee: 5.00,
    discount: 0.50,
    delivery_address: "456 Banani Road, Dhaka 1213",
    payment_method: "cash",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    items: [
      {
        id: "oi_004",
        menu_item_id: "9",
        menu_item_name: "Wagyu Beef Burger",
        menu_item_image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=500&q=80",
        quantity: 1,
        price: 34.99,
      },
      {
        id: "oi_005",
        menu_item_id: "7",
        menu_item_name: "Chocolate Lava Cake",
        menu_item_image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500&q=80",
        quantity: 2,
        price: 9.50,
      },
    ],
    rider: { name: "Sadia Begum", phone: "+880 1900 000789", rating: 5.0 },
  },
];

export const OFFERS = [
  { id: "1", title: "Free Delivery on First Order", subtitle: "Use code WELCOME", emoji: "🚀", bg: "from-orange-500 to-orange-400" },
  { id: "2", title: "20% Off Weekends", subtitle: "Sat & Sun only", emoji: "🎉", bg: "from-purple-600 to-purple-500" },
  { id: "3", title: "Buy 2 Get 1 Free", subtitle: "On selected pizzas", emoji: "🍕", bg: "from-emerald-600 to-emerald-500" },
];
